# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d9389c8d7009df3edec3382435d377318b0afeef018bb18d8fcb7da0d21d2703130de1173109b176f9b4768d087cea2846f14d23d1b44ccc0fd7125534723c8

test:
  secret_key_base: aba395a719ec49271eac99f27580efec721be74d4f364f8b07e8b8b289d7ee1aea1768cfe1f4997a42317bccd49d71a553f00d47684f13760fdd52374f565be2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
